---

- name: Ensure git is installed
  ansible.builtin.package:
    name: git

- name: Ensure golang is installed
  ansible.builtin.package:
    name: golang

- name: Ensure vouch-proxy repository
  ansible.builtin.git:
    repo:    https://github.com/vouch/vouch-proxy.git
    depth:   1
    version: "{{ vouch_proxy_version }}"
    dest:    "{{ vouch_proxy_home }}"

- name: Ensure build vouch-proxy binary
  ansible.builtin.command: 
    cmd:     "{{ vouch_proxy_home }}/do.sh build"
    chdir:   "{{ vouch_proxy_home }}"
    creates: "{{ vouch_proxy_home }}/vouch-proxy"

- name: Ensure install vouch-proxy binary
  ansible.builtin.command: 
    cmd:     "{{ vouch_proxy_home }}/do.sh install"
    chdir:   "{{ vouch_proxy_home }}"
    creates: /bin/vouch-proxy

- name: Ensure vouch-proxy configuration
  ansible.builtin.template:
    src:  config.yml.j2
    dest: "{{ vouch_proxy_home }}/config/config.yml"

- name: Ensure user vouch-proxy
  ansible.builtin.user:
    user:  vouch-proxy
    shell: /usr/sbin/nologin

- name: Ensure vouch-proxy service configuration
  ansible.builtin.template:
    src:  vouch-proxy.service.j2
    dest: /etc/systemd/system/vouch-proxy.service
  notify: restart vouch-proxy

- name: Ensure reload daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Ensure vouch-proxy service is running (and enabled)
  ansible.builtin.service:
    name: vouch-proxy
    state: started
    enabled: yes

...